### ISSUE TITLE
`export` and `serve` create different looking outputs

### ISSUE THREAD

**Issue by gregdan3** [LinuxBozo/jsonresume-theme-kendall#37]
See the issue [here](https://github.com/gregdan3/resume). 

`make init` to set up, then `make build` and check the PDF. It outputs the one column version of this resume theme, but `make serve` produces the two column version of this theme (unless your window is very narrow).

Is there a way to control this behavior? I would prefer to have two column pdf.

**Comment by paskal** [comment]
Could you please attach PDF produced by resume-cli and the PDF made by your browser from served version, so it would be clear what the difference is?

**Comment by gregdan3** [comment]
My bad:

- [html_built_resume.pdf](https://github.com/LinuxBozo/jsonresume-theme-kendall/files/7179987/html_built_resume.pdf)

- [pdf_built_resume.pdf](https://github.com/LinuxBozo/jsonresume-theme-kendall/files/7179919/pdf_built_resume.pdf)

Print to pdf nukes the colors in the html built resume, but the formatting is the same. It uses the two column format, but rendering to a pdf produces a one column output.

Here's the source html (which github forced me to upload as a txt): 
[gregdan3-resume.txt](https://github.com/LinuxBozo/jsonresume-theme-kendall/files/7179998/gregdan3-resume.txt)

**Comment by paskal** [comment]
html_built_resume is the version author intended to have printed and exported as a PDF as far as I know. pdf_built versions definitely look strange, I hope the author will help you make it work properly.

In the meantime, you can use something like [this](https://github.com/paskal/resume/blob/0232c69641f6ac25e943c0dc8576fd8c1eb98e6b/docker-compose.yml#L26-L31) to print the same pdf as html_built_resume.pdf you attached:

```
version: '2'
services:
    build-pdf:
        image: pink33n/html-to-pdf
        command: --url https://terrty.net/cv/verhoturov.html --pdf verhoturov.pdf --scale 1.0
        privileged: true
        volumes:
            - ./:/workspace
```

Scale can be adjusted to make it into the number of pages you desire to have.
